
import { ContentItem, Mood } from "@/types";

// Mock data for recommendations based on mood
export const getMockRecommendations = (mood: Mood): ContentItem[] => {
  const recommendations: Record<Mood, ContentItem[]> = {
    happy: [
      {
        id: "1",
        title: "La La Land",
        type: "movie",
        imageUrl: "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
        description: "A jazz pianist falls for an aspiring actress in Los Angeles.",
        year: 2016,
        genre: "Musical, Romance",
      },
      {
        id: "2",
        title: "Happy by Pharrell Williams",
        type: "music",
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/2/23/Pharrell_Williams_-_Happy.jpg",
        artist: "Pharrell Williams",
        duration: "3:53",
        genre: "Pop, Soul",
      },
      {
        id: "3",
        title: "Cute Puppies Playing",
        type: "youtube",
        imageUrl: "https://i.ytimg.com/vi/j5a0jTc9S10/maxresdefault.jpg",
        duration: "10:15",
      },
      {
        id: "4",
        title: "Mamma Mia!",
        type: "movie",
        imageUrl: "https://image.tmdb.org/t/p/w500/gOm2iJz5gNmB3L4ZKYEKVHdpzSg.jpg",
        description: "The story of a bride-to-be trying to find her real father.",
        year: 2008,
        genre: "Comedy, Musical",
      },
      {
        id: "5",
        title: "Good Vibrations",
        type: "music",
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/e/e8/Good_Vibrations_single.jpg",
        artist: "Beach Boys",
        duration: "3:39",
        genre: "Pop Rock",
      },
      {
        id: "6",
        title: "Upbeat Morning Routine",
        type: "youtube",
        imageUrl: "https://i.ytimg.com/vi/qz4YmD-JFuU/maxresdefault.jpg",
        duration: "15:28",
      },
    ],
    sad: [
      {
        id: "7",
        title: "The Shawshank Redemption",
        type: "movie",
        imageUrl: "https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
        description: "Two imprisoned men bond over a number of years.",
        year: 1994,
        genre: "Drama",
      },
      {
        id: "8",
        title: "Someone Like You",
        type: "music",
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/8/8c/Adele_-_21.png",
        artist: "Adele",
        duration: "4:45",
        genre: "Pop, Soul",
      },
      {
        id: "9",
        title: "Heartwarming Animal Rescues",
        type: "youtube",
        imageUrl: "https://i.ytimg.com/vi/EHrZbS1yjmc/maxresdefault.jpg",
        duration: "12:30",
      },
      {
        id: "10",
        title: "The Fault in Our Stars",
        type: "movie",
        imageUrl: "https://image.tmdb.org/t/p/w500/2y4dmgWYRMYXdD1UyJVcn2HSd1D.jpg",
        description: "Two teenagers share a love that sweeps them on a journey.",
        year: 2014,
        genre: "Drama, Romance",
      },
      {
        id: "11",
        title: "Fix You",
        type: "music",
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/b/b2/Coldplay_X%26Y.svg.png",
        artist: "Coldplay",
        duration: "4:55",
        genre: "Alternative Rock",
      },
      {
        id: "12",
        title: "Motivational Speech Compilation",
        type: "youtube",
        imageUrl: "https://i.ytimg.com/vi/CZlnXWVAmj0/maxresdefault.jpg",
        duration: "20:18",
      },
    ],
    energetic: [
      {
        id: "13",
        title: "The Fast and the Furious",
        type: "movie",
        imageUrl: "https://image.tmdb.org/t/p/w500/lgCEntS9mHagxdL5hb4oiaAcOTC.jpg",
        description: "A police officer infiltrates street racers suspected of theft.",
        year: 2001,
        genre: "Action, Crime, Thriller",
      },
      {
        id: "14",
        title: "Eye of the Tiger",
        type: "music",
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/9/9b/Survivor_-_Eye_Of_The_Tiger.jpg",
        artist: "Survivor",
        duration: "4:05",
        genre: "Rock",
      },
      {
        id: "15",
        title: "Extreme Sports Compilation",
        type: "youtube",
        imageUrl: "https://i.ytimg.com/vi/VoX-qDl-4as/maxresdefault.jpg",
        duration: "14:20",
      },
      {
        id: "16",
        title: "Mad Max: Fury Road",
        type: "movie",
        imageUrl: "https://image.tmdb.org/t/p/w500/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg",
        description: "A post-apocalyptic action film set in a desert wasteland.",
        year: 2015,
        genre: "Action, Adventure",
      },
      {
        id: "17",
        title: "Uptown Funk",
        type: "music",
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/c/c3/Mark_Ronson_-_Uptown_Funk_%28feat._Bruno_Mars%29.png",
        artist: "Mark Ronson ft. Bruno Mars",
        duration: "4:30",
        genre: "Funk, Pop",
      },
      {
        id: "18",
        title: "Parkour in the City",
        type: "youtube",
        imageUrl: "https://i.ytimg.com/vi/i-e2Kqh-6Gk/maxresdefault.jpg",
        duration: "8:45",
      },
    ],
    relaxed: [
      {
        id: "19",
        title: "The Secret Life of Walter Mitty",
        type: "movie",
        imageUrl: "https://image.tmdb.org/t/p/w500/iB3Sr5Cn4dXHjk989vAiOdJj0kL.jpg",
        description: "A daydreamer embarks on a real adventure.",
        year: 2013,
        genre: "Adventure, Comedy, Drama",
      },
      {
        id: "20",
        title: "Weightless",
        type: "music",
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/f/f6/Marconi_union_-_weightless.jpg",
        artist: "Marconi Union",
        duration: "8:09",
        genre: "Ambient",
      },
      {
        id: "21",
        title: "Ocean Scenes with Relaxing Music",
        type: "youtube",
        imageUrl: "https://i.ytimg.com/vi/ky8FvTfQHI4/maxresdefault.jpg",
        duration: "3:00:00",
      },
      {
        id: "22",
        title: "About Time",
        type: "movie",
        imageUrl: "https://image.tmdb.org/t/p/w500/hJ95sIGG7JnPjQVV7AK4WQBlxQz.jpg",
        description: "A young man with the ability to time travel tries to change his past.",
        year: 2013,
        genre: "Comedy, Drama, Fantasy",
      },
      {
        id: "23",
        title: "Claire de Lune",
        type: "music",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Claude_Debussy_atelier_Nadar.jpg/330px-Claude_Debussy_atelier_Nadar.jpg",
        artist: "Claude Debussy",
        duration: "5:07",
        genre: "Classical",
      },
      {
        id: "24",
        title: "Guided Meditation for Sleep",
        type: "youtube",
        imageUrl: "https://i.ytimg.com/vi/aEbJ_maF_fo/maxresdefault.jpg",
        duration: "45:12",
      },
    ],
    focused: [
      {
        id: "25",
        title: "The Social Network",
        type: "movie",
        imageUrl: "https://image.tmdb.org/t/p/w500/jI3H3UVlTpXJbDPbyCb3T6unmTX.jpg",
        description: "Harvard student Mark Zuckerberg creates Facebook.",
        year: 2010,
        genre: "Biography, Drama",
      },
      {
        id: "26",
        title: "Brain Food",
        type: "music",
        imageUrl: "https://i.scdn.co/image/ab67706f00000003e4eadd417a05b2546e866934",
        artist: "Spotify Playlist",
        duration: "3:45:00",
        genre: "Electronic, Ambient",
      },
      {
        id: "27",
        title: "How to Learn Faster",
        type: "youtube",
        imageUrl: "https://i.ytimg.com/vi/CPsxdS8RcDw/maxresdefault.jpg",
        duration: "15:47",
      },
      {
        id: "28",
        title: "A Beautiful Mind",
        type: "movie",
        imageUrl: "https://image.tmdb.org/t/p/w500/zwzWCmH72OSC9NA0ipoqw5Zjya8.jpg",
        description: "The story of John Nash, a mathematical genius.",
        year: 2001,
        genre: "Biography, Drama",
      },
      {
        id: "29",
        title: "Focus",
        type: "music",
        imageUrl: "https://dailymix-images.scdn.co/v2/img/ab6761610000e5eb33b660e6ae5088d3cde6c28c/2/en/default",
        artist: "Various Artists",
        duration: "4:15:00",
        genre: "Instrumental, Ambient",
      },
      {
        id: "30",
        title: "Productivity Tips for Work",
        type: "youtube",
        imageUrl: "https://i.ytimg.com/vi/Qvcx7Y4caQE/maxresdefault.jpg",
        duration: "10:05",
      },
    ],
  };

  return recommendations[mood] || [];
};
